platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

def common_pods
    pod 'Alamofire', '~> 4.2.0'
    pod 'ObjectMapper', '~> 2.2.1'
    pod 'SwiftyJSON', '~> 3.1.3'
    pod 'SnapKit', '~> 3.0.2'
end

def testing_pods
	
end

target 'SwiftNetworkAgent' do
  
  common_pods

  target 'SwiftNetworkAgentTests' do
    inherit! :search_paths
    testing_pods
  end

  target 'SwiftNetworkAgentUITests' do
    inherit! :search_paths
    testing_pods
  end

end
